<?php 
/**
 *	*** DO NOT EDIT THIS FILE ***
 *
 * This file is reserved for adding new functionality in future. 
 *
 * @package   Skyline Theme
 * @version   2.0.0
 * @author    Anand Kumar <anand@blogsynthesis.com>
 * @copyright Copyright (c) 2013, Anand Kumar
 * @link      http://www.blogsynthesis.com/themes/skyline/
 * @license   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 **/

//* Do not remove in order to get support and updates.
add_action( 'genesis_meta', 'wpavenue_meta' );
function wpavenue_meta() {
	echo "<!-- Skyline WordPress Theme v2.0 - by Anand Kumar - http://www.blogsynthesis.com/themes/skyline/ -->\n";
}


/* Do theme setup on the 'after_setup_theme' hook. */
add_action( 'after_setup_theme', 'bowser_jr_theme_setup', 11 );
/**
 * Theme setup function. 
 * @since  0.1.0
 */
function bowser_jr_theme_setup(){

	/* updater args */
	$updater_args = array(
		'repo_uri'   => 'http://my.blogsynthesis.com/',
		'repo_slug'  => 'skyline',
		'username'    => true,
		'dashboard'  => true,
	);

	/* add support for updater */
	add_theme_support( 'auto-hosted-child-theme-updater', $updater_args );
}

/* Load theme updater class */
require_once( trailingslashit( get_stylesheet_directory() ) . 'lib/child-theme-updater.php' );
new Bowser_Jr_Child_Theme_Updater;


//* Child theme (do not remove)
define( 'CHILD_THEME_NAME', 'Skyline Theme' );
define( 'CHILD_THEME_URL', 'http://my.blogsynthesis.com/themes/skyline/' );
define( 'CHILD_THEME_VERSION', '2.0.0' );

//* Add HTML5 markup structure
add_theme_support( 'html5' );

// add_action( 'wp_enqueue_scripts', 'custom_enqueue_script' );
function custom_enqueue_script() {
	wp_enqueue_script( 'custom-script', get_stylesheet_directory_uri() . '/js/custom.js', array( 'jquery' ), '', true );
}

//* Add Genesis Box on Single Posts
// add_action('genesis_entry_content', 'include_share_box', 9 );
function include_share_box() {
    if ( is_single() )
    require(CHILD_DIR.'/sharebar.php');
}

// add_action('wp_footer', 'include_share_js', 9 );
function include_share_js() {
    if ( is_single() )
    require(CHILD_DIR.'/lib/sharebar-js.php');
}
 
genesis_register_sidebar( array(
	'id'				=> 'single-cta',
	'name'			=> __( 'Single CTA', 'wpavenue' ),
	'description'	=> __( 'This is the CTA area on the single posts and pages.', 'wpavenue' ),
) );

genesis_register_sidebar( array(
	'id'				=> 'after-post-entry',
	'name'			=> __( 'After Post Entry', 'wpavenue' ),
	'description'	=> __( 'This is the After Post area on the single posts and pages.', 'wpavenue' ),
) );

//* Add the top widget after the post content
add_action( 'genesis_after_header', 'custom_top_widgets' );
function custom_top_widgets() {
	if ( is_single() || is_archive() ) {
		genesis_widget_area( 'single-cta', array( 'before' => '<div id="single-cta" class="box-section"><div class="wrap">', 'after' => '</div></div>', ) ); 
	}
}

//* Add the top widget after the post content
add_action( 'genesis_before_comments', 'after_post_widgets' );
function after_post_widgets() {
	if ( is_single() ) {
		genesis_widget_area( 'after-post-entry', array( 'before' => '<div id="widget-before-comments" class="box-section"><div class="wrap">', 'after' => '</div></div>', ) ); 
	}
}